# Generated by Django 4.0a1 on 2021-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
    ]
